# Generated by Django 5.0.3 on 2024-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_remove_client_order_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ManyToManyField(to='marketapp.client'),
        ),
    ]
