# Generated by Django 5.0.3 on 2024-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinThrows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_result', models.CharField(max_length=5)),
                ('throw_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
